In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import seaborn as sns
from datetime import timedelta
plt.rc('font', family='NanumBarunGothic')

In [2]:
# Load the dataset
click = pd.read_csv('click_stream_new.csv')

In [3]:
click.head()

,session_id,event_name,event_time,event_id,traffic_source,product_id,quantity,item_price,payment_status,search_keywords,promo_code,promo_amount
0,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,HOMEPAGE,2019-09-06T15:54:32.821085Z,9c4388c4-c95b-4678-b5ca-e9cbc0734109,MOBILE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,SCROLL,2019-09-06T16:03:57.821085Z,4690e1f5-3f99-42d3-84a5-22c4c4d8500a,MOBILE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7d440441-e67a-4d36-b324-80ffd636d166,HOMEPAGE,2019-09-01T12:05:10.322763Z,88aeaeb5-ec98-4859-852c-8abb483faf31,MOBILE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7d440441-e67a-4d36-b324-80ffd636d166,ADD_TO_CART,2019-09-01T12:06:33.322763Z,934e306e-ecc6-472f-9ccb-12c8536910a2,MOBILE,15315.0,4.0,313529.0,NaN,NaN,NaN,NaN
4,7d440441-e67a-4d36-b324-80ffd636d166,BOOKING,2019-09-01T12:15:29.425431Z,9f4767a1-40fa-4c9c-9524-dfad18634d56,MOBILE,NaN,NaN,NaN,Success,NaN,NaN,NaN

In [4]:
#정보확인
click.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12833602 entries, 0 to 12833601
Data columns (total 12 columns):
 #   Column           Dtype
---  ------           -----
 0   session_id       object
 1   event_name       object
 2   event_time       object
 3   event_id         object
 4   traffic_source   object
 5   product_id       float64
 6   quantity         float64
 7   item_price       float64
 8   payment_status   object
 9   search_keywords  object
 10  promo_code       object
 11  promo_amount     float64
dtypes: float64(4), object(8)
memory usage: 1.1+ GB

In [5]:
#결측치 확인
click.isnull().sum()

session_id                0
event_name                0
event_time                0
event_id                  0
traffic_source            0
product_id         10896445
quantity           10896445
item_price         10896445
payment_status     11981020
search_keywords    11660336
promo_code         12507067
promo_amount       12507067
dtype: int64

In [6]:
# 중복값 확인
click.duplicated().sum()

0

In [7]:
# 각 컬럼 내용 확인
print("session_id:", click['session_id'].nunique())
print("event_name:", click['event_name'].unique())
print("event_time:", click['event_time'].nunique())
print("event_id:", click['event_id'].nunique())
print("traffic_source:", click['traffic_source'].unique())
print("product_id:", click['product_id'].nunique())
print("quantity:", click['quantity'].unique())
print("item_price:", click['item_price'].nunique())
print("payment_status:", click['payment_status'].unique())
print("search_keywords:", click['search_keywords'].unique())
print("promo_code:", click['promo_code'].unique())
print("promo_amount:", click['promo_amount'].nunique())

session_id: 895203
event_name: ['HOMEPAGE' 'SCROLL' 'ADD_TO_CART' 'BOOKING' 'SEARCH' 'ITEM_DETAIL'
 'ADD_PROMO' 'CLICK' 'PROMO_PAGE']
event_time: 12814223
event_id: 12833602
traffic_source: ['MOBILE' 'WEB']
product_id: 44446
quantity: [nan  4.  2.  1.  3.  7. 16.  6. 14.  5. 10.  8.  9. 11. 19. 17. 13. 20.
 15. 22. 12. 18. 33. 27. 21. 28. 23. 26. 34. 25. 40. 29. 24. 35. 38. 41.
 31. 39. 36. 32. 30. 48. 37. 42. 43.]
item_price: 460872
payment_status: [nan 'Success' 'Failed']
search_keywords: [nan 'Dress Kondangan' 'Tas Wanita' 'Celana Panjang' 'Kaos' 'Sepatu'
 'Tas Kerja' 'T-Shirt' 'Topi' 'Bekas' 'Baju' 'Thrift' 'Sepatu Nike'
 'Dress Pesta' 'Sepatu Adidas' 'Second' 'T-shirt' 'Jam' 'Celana'
 'Second Hand' 'Barang Bekas' 'Sendal' 'Daster' 'Baju Tidur']
promo_code: [nan 'AZ2022' 'BUYMORE' 'WEEKENDSERU' 'XX2022' 'LIBURDONG' 'WEEKENDMANTAP'
 'STARTUP' 'SC2022']
promo_amount: 15179

In [8]:
# 날짜 전처리
click['event_time'] = pd.to_datetime(click['event_time'])

In [9]:
# float64값 int로 데이터 타입 변경 및 결측치 0으로 처리
click['product_id'] = click['product_id'].fillna(0).astype(int)
click['quantity'] = click['quantity'].fillna(0).astype(int)
click['item_price'] = click['item_price'].fillna(0).astype(int)
click['promo_amount'] = click['promo_amount'].fillna(0).astype(int)

# promo_code 결측치 nopromo로 변경
click['promo_code'].fillna('nopromo', inplace=True)

# search_keywords 결측치 no로 변경
#click['search_keywords'].fillna('no', inplace=True)

In [10]:
click.head(20)

,session_id,event_name,event_time,event_id,traffic_source,product_id,quantity,item_price,payment_status,search_keywords,promo_code,promo_amount
0,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,HOMEPAGE,2019-09-06 15:54:32.821085+00:00,9c4388c4-c95b-4678-b5ca-e9cbc0734109,MOBILE,0,0,0,NaN,NaN,nopromo,0
1,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,SCROLL,2019-09-06 16:03:57.821085+00:00,4690e1f5-3f99-42d3-84a5-22c4c4d8500a,MOBILE,0,0,0,NaN,NaN,nopromo,0
2,7d440441-e67a-4d36-b324-80ffd636d166,HOMEPAGE,2019-09-01 12:05:10.322763+00:00,88aeaeb5-ec98-4859-852c-8abb483faf31,MOBILE,0,0,0,NaN,NaN,nopromo,0
3,7d440441-e67a-4d36-b324-80ffd636d166,ADD_TO_CART,2019-09-01 12:06:33.322763+00:00,934e306e-ecc6-472f-9ccb-12c8536910a2,MOBILE,15315,4,313529,NaN,NaN,nopromo,0
4,7d440441-e67a-4d36-b324-80ffd636d166,BOOKING,2019-09-01 12:15:29.425431+00:00,9f4767a1-40fa-4c9c-9524-dfad18634d56,MOBILE,0,0,0,Success,NaN,nopromo,0
5,7d440441-e67a-4d36-b324-80ffd636d166,SEARCH,2019-09-01 12:07:00.322763+00:00,c952142b-4fe9-4694-ad7f-21a5d1bed9ca,MOBILE,0,0,0,NaN,Dress Kondangan,nopromo,0
6,7d440441-e67a-4d36-b324-80ffd636d166,HOMEPAGE,2019-09-01 12:08:27.322763+00:00,365b3840-9647-4bf5-917f-f0bec3d05332,MOBILE,0,0,0,NaN,NaN,nopromo,0
7,7d440441-e67a-4d36-b324-80ffd636d166,ITEM_DETAIL,2019-09-01 12:09:49.322763+00:00,1a1e3548-108e-4520-bf04-1b01d43a72cb,MOBILE,0,0,0,NaN,NaN,nopromo,0
8,7d440441-e67a-4d36-b324-80ffd636d166,SCROLL,2019-09-01 12:11:06.322763+00:00,f7246095-b094-46c1-b2ac-bcfd080146c3,MOBILE,0,0,0,NaN,NaN,nopromo,0
9,7d440441-e67a-4d36-b324-80ffd636d166,ITEM_DETAIL,2019-09-01 12:12:19.322763+00:00,74a000dc-b931-4c59-abcc-02e991623bc1,MOBILE,0,0,0,NaN,NaN,nopromo,0
10,7d440441-e67a-4d36-b324-80ffd636d166,ITEM_DETAIL,2019-09-01 12:13:36.322763+00:00,85b3589a-5281-48a2-b2f3-a39a7de69f60,MOBILE,0,0,0,NaN,NaN,nopromo,0
11,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,HOMEPAGE,2019-09-09 04:49:02.425431+00:00,177faf86-4afe-4214-91f5-dde253b7984d,MOBILE,0,0,0,NaN,NaN,nopromo,0
12,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 05:06:03.425431+00:00,c1b42157-39a7-4521-a4dc-ed0200de301a,MOBILE,6133,2,249443,NaN,NaN,nopromo,0
13,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 05:23:36.425431+00:00,61cbe834-c585-406e-8eac-30f671e51fbb,MOBILE,6721,1,134504,NaN,NaN,nopromo,0
14,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 05:42:03.425431+00:00,2bd3f01a-e062-4c13-8b9d-598fb5379ed2,MOBILE,57622,1,384716,NaN,NaN,nopromo,0
15,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 05:58:58.425431+00:00,ba1c5f20-869a-42be-878c-75496c28aba3,MOBILE,5490,1,121318,NaN,NaN,nopromo,0
16,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 06:16:07.425431+00:00,b72d14a0-15d4-4099-89ce-76aba204538f,MOBILE,21304,1,209086,NaN,NaN,nopromo,0
17,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 06:32:41.425431+00:00,29d5034a-c2ba-4e2f-abdd-3b4a81dbda78,MOBILE,12106,1,184033,NaN,NaN,nopromo,0
18,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 06:49:47.425431+00:00,5cf07ed1-a2f7-4918-b639-a101d6eac14e,MOBILE,59647,1,311267,NaN,NaN,nopromo,0
19,f7b5cd60-4f87-4b3c-8bde-c7da8930eec2,ADD_TO_CART,2019-09-09 07:05:44.425431+00:00,107cc669-e607-4478-9ee8-e7619a68a7c5,MOBILE,24105,1,216070,NaN,NaN,nopromo,0

In [11]:
#결측치 확인
click.isnull().sum()

session_id                0
event_name                0
event_time                0
event_id                  0
traffic_source            0
product_id                0
quantity                  0
item_price                0
payment_status     11981020
search_keywords    11660336
promo_code                0
promo_amount              0
dtype: int64

# 추가분석작업

In [13]:
click['event_time'] = pd.to_datetime(click['event_time'])

In [14]:
click.head()

,session_id,event_name,event_time,event_id,traffic_source,product_id,quantity,item_price,payment_status,search_keywords,promo_code,promo_amount
0,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,HOMEPAGE,2019-09-06 15:54:32.821085+00:00,9c4388c4-c95b-4678-b5ca-e9cbc0734109,MOBILE,0,0,0,NaN,NaN,nopromo,0
1,fb0abf9e-fd1a-44dd-b5c0-2834d5a4b81c,SCROLL,2019-09-06 16:03:57.821085+00:00,4690e1f5-3f99-42d3-84a5-22c4c4d8500a,MOBILE,0,0,0,NaN,NaN,nopromo,0
2,7d440441-e67a-4d36-b324-80ffd636d166,HOMEPAGE,2019-09-01 12:05:10.322763+00:00,88aeaeb5-ec98-4859-852c-8abb483faf31,MOBILE,0,0,0,NaN,NaN,nopromo,0
3,7d440441-e67a-4d36-b324-80ffd636d166,ADD_TO_CART,2019-09-01 12:06:33.322763+00:00,934e306e-ecc6-472f-9ccb-12c8536910a2,MOBILE,15315,4,313529,NaN,NaN,nopromo,0
4,7d440441-e67a-4d36-b324-80ffd636d166,BOOKING,2019-09-01 12:15:29.425431+00:00,9f4767a1-40fa-4c9c-9524-dfad18634d56,MOBILE,0,0,0,Success,NaN,nopromo,0

In [15]:
click['search_keywords'].value_counts()

search_keywords
Dress Kondangan    256194
Tas Wanita         128790
Bekas              112269
T-Shirt            100087
Baju                83873
Kaos                83759
Dress Pesta         76829
Sepatu Nike         51578
Tas Kerja           38677
Second Hand         28429
Second              28195
Thrift              28171
Sepatu              28029
Celana Panjang      28009
Barang Bekas        27818
Sepatu Adidas       25627
Sendal              12787
Celana              11739
T-shirt              7097
Jam                  7000
Topi                 4844
Baju Tidur           2268
Daster               1197
Name: count, dtype: int64

In [16]:
brand_mapping = {
    'Bekas': 'Bekas', 'Second Hand': 'Bekas', 'Second': 'Bekas', 'Thrift': 'Bekas', 'Barang Bekas': 'Bekas'
}

click['search_keywords'] = click['search_keywords'].replace(brand_mapping, regex=True)

In [17]:
click['search_keywords'].value_counts()

search_keywords
Dress Kondangan    256194
Bekas              224882
Tas Wanita         128790
T-Shirt            100087
Baju                83873
Kaos                83759
Dress Pesta         76829
Sepatu Nike         51578
Tas Kerja           38677
Sepatu              28029
Celana Panjang      28009
Sepatu Adidas       25627
Sendal              12787
Celana              11739
T-shirt              7097
Jam                  7000
Topi                 4844
Baju Tidur           2268
Daster               1197
Name: count, dtype: int64

In [18]:
click_r = click

In [19]:
# 섹션으 시작 시간과 끝나는 시간 계산
session_st = click_r.groupby('session_id')['event_time'].min()
session_et = click_r.groupby('session_id')['event_time'].max()

# 섹션 시간 저장
click_r['session_t'] = click_r['session_id'].map(session_et - session_st)

# 전체 평균 체류시간을 계산
ast = click_r['session_t'].mean()

print("평균 체류 :", ast)

평균 체류 : 11 days 15:06:28.849329409

In [20]:
click_r.describe()

,product_id,quantity,item_price,promo_amount,session_t
count,1.283360e+07,1.283360e+07,1.283360e+07,1.283360e+07,12833602
mean,4.395727e+03,2.173362e-01,4.039879e+04,1.356625e+02,11 days 15:06:28.849329409
std,1.234690e+04,7.747922e-01,1.062442e+05,9.392033e+02,28 days 08:02:33.761425387
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0 days 00:00:00
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1 days 02:04:22
50%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4 days 05:47:09
75%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,11 days 11:21:55
max,6.000000e+04,4.800000e+01,1.335959e+06,2.451900e+04,944 days 16:22:19

In [21]:
click_t = click_r

In [22]:
# session_id와 event_time을 기준으로 정렬
df = click_t.sort_values(['session_id', 'event_time'])

# 이전 row의 event_time을 저장할 변수 초기화
pre_event_time = None

# session_id에 번호를 붙일 변수 초기화
session_num = 1

# session_id가 같은 경우, event_time 차이를 계산하고 번호를 붙임
for i, row in df.iterrows():
    if pre_event_time is not None and row['session_id'] == pre_session_id:
        time_diff = row['event_time'] - pre_event_time
        if time_diff >= timedelta(minutes=30):
            session_num += 1
    df.at[i, 'session_id'] = f"{row['session_id']}_{session_num}"
    pre_event_time = row['event_time']
    pre_session_id = row['session_id']

# 결과 출력
print(df)

                                           session_id   event_name  \
469318         00001f29-3ede-4445-95f0-0178934e32ba_1     HOMEPAGE
469319         00001f29-3ede-4445-95f0-0178934e32ba_2  ADD_TO_CART
469321         00001f29-3ede-4445-95f0-0178934e32ba_2     HOMEPAGE
469322         00001f29-3ede-4445-95f0-0178934e32ba_3        CLICK
469323         00001f29-3ede-4445-95f0-0178934e32ba_4        CLICK
...                                               ...          ...
5928943  fffffaf6-55ee-428b-a3bf-075cd7f1a093_8470219  ITEM_DETAIL
5928944  fffffaf6-55ee-428b-a3bf-075cd7f1a093_8470220  ITEM_DETAIL
5928945  fffffaf6-55ee-428b-a3bf-075cd7f1a093_8470221  ITEM_DETAIL
5928946  fffffaf6-55ee-428b-a3bf-075cd7f1a093_8470222   PROMO_PAGE
5928947  fffffaf6-55ee-428b-a3bf-075cd7f1a093_8470223        CLICK

                              event_time  \
469318  2019-05-17 11:51:52.276396+00:00
469319  2019-05-17 19:54:53.276396+00:00
469321  2019-05-17 19:55:12.276396+00:00
469322  2019-05-18 03:58:25.276396+00:00
469323  2019-05-18 12:02:44.276396+00:00
...                                  ...
5928943 2018-08-20 13:46:27.790374+00:00
5928944 2018-08-22 09:00:29.790374+00:00
5928945 2018-08-24 04:20:30.790374+00:00
5928946 2018-08-25 23:35:58.790374+00:00
5928947 2018-08-27 18:51:50.790374+00:00

                                     event_id traffic_source  product_id  \
469318   51793173-664c-4557-8a06-fc37587bea3d         MOBILE           0
469319   517b331c-4296-4772-a1a2-9bf7500a5570         MOBILE       33855
469321   2c0581d2-3185-4172-87ea-795ee26a4d0a         MOBILE           0
469322   81982a1d-5562-44e8-8b1d-1c3366434c5e         MOBILE           0
469323   6f7980bf-dce4-4b1e-9ffa-5c37499c4dc7         MOBILE           0
...                                       ...            ...         ...
5928943  0f3593ec-5341-4cee-b119-79dfd266911a         MOBILE           0
5928944  24415771-d466-41a1-8cfb-aa6dc8f6cb40         MOBILE           0
5928945  d52f1455-633d-448b-a704-c68ac1bd8156         MOBILE           0
5928946  7689a2ca-e91e-4f79-97ae-f702c153ed6b         MOBILE           0
5928947  37eb4f78-92aa-4114-9e9c-7590a868c809         MOBILE           0

         quantity  item_price payment_status search_keywords promo_code  \
469318          0           0            NaN             NaN    nopromo
469319          6      237967            NaN             NaN    nopromo
469321          0           0            NaN             NaN    nopromo
469322          0           0            NaN             NaN    nopromo
469323          0           0            NaN             NaN    nopromo
...           ...         ...            ...             ...        ...
5928943         0           0            NaN             NaN    nopromo
5928944         0           0            NaN             NaN    nopromo
5928945         0           0            NaN             NaN    nopromo
5928946         0           0            NaN             NaN    nopromo
5928947         0           0            NaN             NaN    nopromo

         promo_amount        session_t
469318              0  2 days 08:25:12
469319              0  2 days 08:25:12
469321              0  2 days 08:25:12
469322              0  2 days 08:25:12
469323              0  2 days 08:25:12
...               ...              ...
5928943             0 43 days 22:57:14
5928944             0 43 days 22:57:14
5928945             0 43 days 22:57:14
5928946             0 43 days 22:57:14
5928947             0 43 days 22:57:14

[12833602 rows x 13 columns]

In [23]:
# 각 세션의 시작 시간과 종료 시간 계산
session_st2 = df.groupby('session_id')['event_time'].min()
session_et2 = df.groupby('session_id')['event_time'].max()

# 세션의 지속 시간 계산 및 exist_time 열 생성
df['session_t'] = df['session_id'].map(session_et2 - session_st2)

# 평균 체류 시간 계산
ast2 = df['session_t'].mean()

print("평균 체류 시간 :", ast2)

평균 체류 시간 : 0 days 00:49:11.762441822

In [24]:
before_ids = click_r['session_id'].nunique()
unique_session_ids = df['session_id'].nunique()

print("기존 session_id의 개수:", before_ids)
print("새로 정의한 session_id의 개수:", unique_session_ids)

기존 session_id의 개수: 895203
새로 정의한 session_id의 개수: 9365425

In [25]:
df.to_csv('model2_new_session_id.csv',index = False)